Sprint 04
TMWF/MovieQuiz-ios pull request #1
Opened 2022-11-17 16:51 UTC by TMWF

2022-11-17 17:57 UTC, mmbabaev commented
Также шрифты не меняются в приложении. В учебнике допущена ошибка, поэтому этот пункт необязателен. 
На скрине показал как нужно сделать: 
1) Шрифты добавлены в Group (серая папка)
2) Шрифтам проставлена галочка Target Membership  (справа)

<img width="1356" alt="Screen Shot 2022-11-17 at 20 15 01" src="https://user-images.githubusercontent.com/12600807/202513128-d74c5681-7a76-4778-ae5b-0fbcd44f0893.png">

Полезная статья, которая помогла мне разобраться в свое время: 
https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/

2022-11-17 17:58 UTC, mmbabaev commented
<img width="534" alt="Screen Shot 2022-11-17 at 20 55 55" src="https://user-images.githubusercontent.com/12600807/202521788-3d4ac8ab-4852-49a1-81e7-24f080f83ce4.png">
обязательное замечание: нужно испавить сжимание label на iphone 13 mini

2022-11-17 17:58 UTC, mmbabaev requested changes

2022-11-17 17:58 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-17 21:17 UTC, TMWF commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Благодарю, баг с кнопками исправил, лэйбл с вопросом теперь корректно отображается на мини. За ссылку по шрифтам отдельное спасибо.

2022-11-17 21:17 UTC, closed without merging

2022-11-18 15:13 UTC, mmbabaev commented
<img width="396" alt="Screen Shot 2022-11-18 at 18 11 56" src="https://user-images.githubusercontent.com/12600807/202737160-4b93d5bf-c594-45a0-9467-89957525be2a.png">

Сейчас сплюснулся верхний label "Вопрос" 

<img width="313" alt="Screen Shot 2022-11-18 at 18 13 00" src="https://user-images.githubusercontent.com/12600807/202737352-04fda783-5d49-40c9-8aed-789b98277394.png">

тут нужно занулить top + bottom constraint